package:
  name: osqp
  version: "0.3.1"

source:
  git_url: https://github.com/oxfordcontrol/osqp-python.git
  git_rev: v0.3.1


requirements:
  build:
    - python
    - setuptools
    - future
    - numpy >=1.7
    - scipy >=0.13.2

  run:
    - python
    - future
    - numpy >=1.7
    - scipy >=0.13.2

test:
  # Python imports
  imports:
    - osqp

about:
  home: http://osqp.readthedocs.io/
  license: Apache 2.0
  license_file: LICENSE
  summary: 'OSQP: The Operator Splitting QP Solver'
