name: Pre-commit checks

on:
  push:
    # Run this workflow on all branches because it is good to flag these errors
    # and this workflow is "cheap"
    branches:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  precommit:
    name: Pre-commit checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v6
      name: Install Python
      with:
        python-version: '3.9'

    - name: Install package with dev dependencies
      run: |
        python -m pip install .[dev]

    - name: Pre-commit checks
      run: |
        pre-commit run --all-files
